[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/plugins/iceberg.rc.vim
'''

[[plugins]]
repo = 'majutsushi/tagbar'


[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-thems']
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
let g:airline_theme='luna'
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nmap [figitive] <Nop>
    map <Leader>g [figitive]
    nnoremap <silent> [figitive]c :<C-u>Gcommit<CR>
    nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
    nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
    nnoremap <silent> [figitive]l :<C-u>Glog<CR>
'''


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <Space>n :<C-u>NERDTreeToggle<CR>
    let NERDTreeIgnore=['\.pyc$', '__pycache__']
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    nnoremap <silent> <Leader>w :FixWhitespace<CR>
'''

[[plugins]]
repo = 'lambdalisue/vim-gista'
hook_add = '''
    let g:gista#client#default_username = 'lighttiger2505'
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
    source ~/.config/nvim/plugins/openbrowser.rc.vim
'''
